dependencies {
    implementation libs.jobj.core
    implementation libs.jobj.reflect
    implementation libs.jobj.copy
    implementation libs.silly.collection
    implementation libs.silly.math
    implementation libs.vintage.time
    testImplementation libs.commons.lang3
    testImplementation libs.equalsverifier
    testImplementation libs.silly.strings
    testImplementation libs.test.object
    testImplementation libs.meanbean
    // Note: use of bundles...
    testImplementation libs.bundles.unit.testing
    testRuntimeOnly libs.junit.platform.launcher
}
