[versions]
commons-lang3-version = "3.14.0"
equalsverifier-version = "3.16.1"
gradle-plugin-grgit-version = "5.2.2"
gradle-plugin-license-version = "0.16.1"
gradle-plugin-spotless-version = "7.0.0.BETA1"
gradle-plugin-version-catalog-update-version = "0.8.4"
gradle-plugin-versions-version = "0.51.0"
jobj-copy-version = "4.2"
jobj-core-version = "8.2"
jobj-reflect-version = "2.4"
junit-jupiter-params-version = "5.11.0-M2"
junit-jupiter-version = "5.11.0-M2"
junit-platform-launcher-version = "1.11.0-M2"
meanbean-version = "3.0.0-M9"
silly-collection-version = "27.1"
silly-math-version = "2.3"
silly-strings-version = "9.1"
test-object-version = "8.2"
vintage-time-version = "6"

[libraries]
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3-version" }
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsverifier-version" }
jobj-copy = { module = "io.github.astrapi69:jobj-copy", version.ref = "jobj-copy-version" }
jobj-core = { module = "io.github.astrapi69:jobj-core", version.ref = "jobj-core-version" }
jobj-reflect = { module = "io.github.astrapi69:jobj-reflect", version.ref = "jobj-reflect-version" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter-version" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter-params-version" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher-version" }
meanbean = { module = "com.github.meanbeanlib:meanbean", version.ref = "meanbean-version" }
silly-collection = { module = "io.github.astrapi69:silly-collection", version.ref = "silly-collection-version" }
silly-math = { module = "io.github.astrapi69:silly-math", version.ref = "silly-math-version" }
silly-strings = { module = "io.github.astrapi69:silly-strings", version.ref = "silly-strings-version" }
test-object = { module = "io.github.astrapi69:test-object", version.ref = "test-object-version" }
vintage-time = { module = "io.github.astrapi69:vintage-time", version.ref = "vintage-time-version" }

[bundles]
unit-testing = [
    "junit-jupiter",
    "junit-jupiter-params",
    "meanbean",
    "test-object",
]

[plugins]
gradle-versions-plugin = { id = "com.github.ben-manes.versions", version.ref = "gradle-plugin-versions-version" }
grgit-gradle = { id = "org.ajoberstar.grgit", version.ref = "gradle-plugin-grgit-version" }
license-gradle-plugin = { id = "com.github.hierynomus.license", version.ref = "gradle-plugin-license-version" }
spotless-plugin-gradle = { id = "com.diffplug.spotless", version.ref = "gradle-plugin-spotless-version" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "gradle-plugin-version-catalog-update-version" }
